SELECT 
    oa.razao_social AS operadora,
    SUM(d.vl_saldo_final) AS total_despesas
FROM (
    SELECT * FROM despesas_1t_2024 WHERE descricao = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR '
    UNION ALL
    SELECT * FROM despesas_2t_2024 WHERE descricao = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR '
    UNION ALL
    SELECT * FROM despesas_3t_2024 WHERE descricao = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR '
    UNION ALL
    SELECT * FROM despesas_4t_2024 WHERE descricao = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR '
) d
JOIN operadoras_ativas oa ON d.reg_ans = oa.registro_ans
GROUP BY oa.razao_social
ORDER BY total_despesas DESC
LIMIT 10;


